# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9b0639332e4ef34778175dfb5c39bd54c433992ebb490ca33b18376f326bbd8d871047de28569bfca72365a2e271edffee1c84b4cdb31f0aea85f3dd34c61ab

test:
  secret_key_base: 8896cecb6ffa32ab9d2dc6f7d7717673db88c994a0b1ee37b3d348599eb6e532fc7ec861c0de156a82811d3da01a466592822edacebffb24f7b730bcc475fb56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
